### ISSUE TITLE
tensorflow-1-public/C1/W2/assignment/C1_W2_Assignment_Solution.ipynb reading item

### ISSUE THREAD

**Issue by gladwig2** [https-deeplearning-ai/tensorflow-1-public#10]
![image](https://user-images.githubusercontent.com/8951837/129582898-2be6c9f9-cf2f-4ad2-a6aa-17c176e5c9b4.png)

This code does not run and does not match the assignment.

![image](https://user-images.githubusercontent.com/8951837/129583403-18c7d224-3cd2-4ec3-b59d-953464146776.png)

1) the assignment has a subroutine
![image](https://user-images.githubusercontent.com/8951837/129584166-0dd63746-52ce-42b0-b96f-07151e909837.png)
while the above code does not

2) the  following code fails:
![image](https://user-images.githubusercontent.com/8951837/129584295-3fb53945-72ef-46ac-9baf-883d5b90e5cd.png)

I see the github repository has a note about  logs.get('accuracy'), but it is not in the course version.

**Comment by cfav-dev** [comment]
Hello! We're currently discussing resolution on solution notebooks. Thanks.
