### ISSUE TITLE
Minor typo in C4_W2_Lab_3_deep_NN.ipynb

### ISSUE THREAD

**Issue by holleyism** [https-deeplearning-ai/tensorflow-1-public#105]
In the 3rd to last markdown cell, the fifth word is missing a letter.  Alternatively, the typo appears on line 696 of the raw ipynb file.

```You can get the preictions again and overlay it on the validation set.```

should be:

```You can get the predictions again and overlay it on the validation set.```

**Comment by holleyism** [comment]
Just adding a comment to avoid a separate issue.   There's another typo in C4_W3_Lab_1_RNN.ipynb line 346.  "routs" I believe should be "routes".

**Comment by holleyism** [comment]
Also in C4W4_Assignment.ipynb, on line 276, "dinamically" should be "dynamically".

**Comment by cfav-dev** [comment]
Thank you! Next time, you can also post feedback in the community for better visibility. There are instructions in Week 1 on how to join. Thanks again!
