### ISSUE TITLE
Typo in C4_W4_Lab_3_Sunspots_CNN_RNN_DNN

### ISSUE THREAD

**Issue by h93xV2** [https-deeplearning-ai/tensorflow-1-public#108]
In the C4_W4_Lab_3_Sunspots_CNN_RNN_DNN notebook, there's a small typo. It says:
> As mentioned in the lectures, if your results don't good, you can try tweaking the parameters here and see if the model will learn better.

The part which doesn't look right is `don't good`. I'm not sure what the author intended to write, but it seems like it's missing a verb like `look`:
> As mentioned in the lectures, if your results don't look good, you can try tweaking the parameters here and see if the model will learn better.

**Comment by cfav-dev** [comment]
Thank you! Next time, you can also post feedback in the community for better visibility. There are instructions in Week 1 on how to join.
