### ISSUE TITLE
Small Typo in C3W3_Assignment.ipynb

### ISSUE THREAD

**Issue by OmarElgammal1** [https-deeplearning-ai/tensorflow-1-public#110]
In the global variables markdown cell, OOV_TOKEN line, it should be written as:
Defaults to `\"\<OOV>\"`.
There is an extra `\` in the middle.

**Comment by cfav-dev** [comment]
Thank you, Omar! Next time, you can also post feedback in the community for better visibility. There are instructions in Week 1 on how to join. Thanks again!
