### ISSUE TITLE
Course 3 - Week 3 - Lesson 1c Using Deprecated Function

### ISSUE THREAD

**Issue by RyoKusnadi** [https-deeplearning-ai/tensorflow-1-public#18]
Hi Deep Learning.AI Team,

For the below code,
```
train_dataset = train_dataset.padded_batch(BATCH_SIZE, train_dataset.output_shapes)
test_dataset = test_dataset.padded_batch(BATCH_SIZE, test_dataset.output_shapes)
```
it uses the deprecated function "output_shapes", so all users that use TF2.0 cannot run the cell

**Comment by Mubsi** [comment]
Hi @RyoKusnadi,

Please follow this repository for the specialisation and the file names used in it.

I believe you are referring to this [notebook](https://github.com/https-deeplearning-ai/tensorflow-1-public/blob/main/C3/W3/ungraded_labs/C3_W3_Lab_3_multiple_layer_GRU.ipynb), and the code in here is up to date to run with the latest TF version.
