### ISSUE TITLE
Syntax error in the window function

### ISSUE THREAD

**Issue by MohamedNedal** [https-deeplearning-ai/tensorflow-1-public#31]
Hello, in the notebook **C4_W4_Lab_2_Sunspots.ipynb** , in the _windowed_dataset_ function, I think that line: 
`    ds = ds.map(lambda w: (w[:-1], w[1:]))
`
should be like this: 
`    ds = ds.map(lambda w: (w[:-1], w[-1:])) 
`
Can you please confirm?

**Comment by andres-zartab** [comment]
Thanks! This has been updated in the latest version of the course
