### ISSUE TITLE
C1_W4_Lab_2_image_generator_with_validation.ipynb name error

### ISSUE THREAD

**Issue by booroono** [https-deeplearning-ai/tensorflow-1-public#36]
# Set up matplotlib fig, and size it to fit 4x4 pics
next_horse_pix = [os.path.join(train_horse_dir, fname) 
                for fname in val_horse_names[pic_index-8:pic_index]]
next_human_pix = [os.path.join(train_human_dir, fname) 
                for fname in val_human_names[pic_index-8:pic_index]]

should be chaned as below:

next_horse_pix = [os.path.join(train_horse_dir, fname) 
                for fname in **train_horse_names**[pic_index-8:pic_index]]
next_human_pix = [os.path.join(train_human_dir, fname) 
                for fname in **train_human_names**[pic_index-8:pic_index]]

**Comment by cfav-dev** [comment]
Hi! Thank you for reporting! This has now been fixed!
