### ISSUE TITLE
Getting error while trying to download file from drive

### ISSUE THREAD

**Issue by coolsaiification** [https-deeplearning-ai/tensorflow-1-public#37]
Executing this command as per [C1_W4_Lab_1_image_generator_no_validation.ipynb](https://github.com/https-deeplearning-ai/tensorflow-1-public/blob/main/C1/W4/ungraded_labs/C1_W4_Lab_1_image_generator_no_validation.ipynb): `!gdown --id 1onaG42NZft3wCE1WH0GDEbUhu75fedP5`

Getting the following error:
```
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1onaG42NZft3wCE1WH0GDEbUhu75fedP5 
```

**Comment by eccemerrin** [comment]
Yeah me too.

**Comment by cfav-dev** [comment]
Hi! Thank you for reporting. We added a workaround to download the dataset. Please reopen the colab. Hope it also works on your end! Thanks again!
