### ISSUE TITLE
!gdown  command not working

### ISSUE THREAD

**Issue by iamdouli** [https-deeplearning-ai/tensorflow-1-public#42]
when running the cell to download "cats_and_dogs_filtered.zip" file an error occurs saying:

> Access denied with the following error:
> 
>  	Cannot retrieve the public link of the file. You may need to change
> 	the permission to 'Anyone with the link', or have had many accesses. 
> 
> You may still be able to access the file from the browser:
> 
> 	 https://drive.google.com/uc?id=1RL0T7Rg4XqQNRCkjfnLo4goOJQ7XZro9

**Comment by andres-zartab** [comment]
Hi @iamdouli, in which notebook are you facing this issue?

**Comment by andres-zartab** [comment]
Try replacing the gdown command with this one: `!wget --no-check-certificate https://storage.googleapis.com/mledu-datasets/cats_and_dogs_filtered.zip`

**Comment by iamdouli** [comment]
Hi @andres-zartab, the issue is in `C2_W4_Lab_1_multi_class_classifier`, and `C2_W3_Lab_1_transfer_learning` notebooks and maybe others too. Thanks for your help, your solution solves the issue with second notebook, the other one I used the code below as workaournd.

```
%%writefile download.sh

#!/bin/bash
fileid="FILE_ID"
filename="FILE_NAME.zip"
html=`curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id=${fileid}"`
curl -Lb ./cookie "https://drive.google.com/uc?export=download&`echo ${html}|grep \-Po '(confirm=[a-zA-Z0-9\-_]+)'`&id=${fileid}" -o ${filename}

!bash download.sh
```

**Comment by cfav-dev** [comment]
Hi @iamdouli ! We just replaced the gdown commands for the C2 W4 notebooks. Kindly reopen it from the classroom to see the changes. We will make an audit of the other notebooks soon as well so we can avoid this issue with the gdown commands. Thank you!
