### ISSUE TITLE
Lab for C2_W2_Lab_1_cats_v_dogs_augmentation.ipynb

### ISSUE THREAD

**Issue by naiborhujosua** [https-deeplearning-ai/tensorflow-1-public#45]
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You might allow access in order to avoid downloading files of which size is big.

**Comment by cfav-dev** [comment]
Hi! Thank you for reporting. This has now been fixed!
