### ISSUE TITLE
output not cleared in installed version

### ISSUE THREAD

**Issue by gladwig2** [https-deeplearning-ai/tensorflow-1-public#6]
When I opened the first assignment, there were error messages on the output of some of the cells.

This would not appear in the github version- but in the file installed on Coursera. It looked like once the file was installed, maybe it was run without a library install?  
Anyway, Just need to clear the output and save the file on the Coursera image.

I would provide a image of the error messages, but once I ran the file, the copy in my container changed.

**Comment by cfav-dev** [comment]
Fixed! Thanks!
