### ISSUE TITLE
tensorflow-1-public/C1/W2/ungraded_labs/C1_W2_Lab_1_beyond_hello_world.ipynb  [Somewhere]

### ISSUE THREAD

**Issue by gladwig2** [https-deeplearning-ai/tensorflow-1-public#7]
![image](https://user-images.githubusercontent.com/8951837/129572511-85822aad-6cb2-4465-9221-d86cec4eb525.png)

I imagine this [Somewhere] was meant to be a link to another place in the course?

This is in: 
![image](https://user-images.githubusercontent.com/8951837/129572797-26e72ae5-756e-41c9-93ed-989d804c164b.png)

**Comment by cfav-dev** [comment]
Hi Geoff! Thanks for submitting the issues and sorry for the delay. Will be handling the maintenance now. I looked at the notebook and it looks like it has already been revised previously.
