### ISSUE TITLE
C2W1_Assignment.ipynb: Expected Output is wrong

### ISSUE THREAD

**Issue by hiroshiichise** [https-deeplearning-ai/tensorflow-1-public#72]
The number of images should be 12500, not 12501

```
Expected Output:

There are 12501 images of dogs.
There are 12501 images of cats.

```

In the Dog and Cat directory in the Zip there are 12501 files.
However, after extracting the Zip to tmp, Thumbs.db is deleted by under code, so the file count is 12500.

```
# Deletes all non-image files (there are two .db files bundled into the dataset)
!find /tmp/PetImages/ -type f ! -name "*.jpg" -exec rm {} +
```

**Comment by cfav-dev** [comment]
Thank you! This has now been fixed!
