### ISSUE TITLE
C1_W2_Lab_1_beyond_hello_world.ipynb Error in tf.keras.activation.softmax

### ISSUE THREAD

**Issue by abhiseketan5** [https-deeplearning-ai/tensorflow-1-public#86]
input to softmax function: [1. 3. 4. 2.]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[~\AppData\Local\Temp\ipykernel_21880\3343928682.py](https://file+.vscode-resource.vscode-cdn.net/d%3A/resoluteai/coursera/~/AppData/Local/Temp/ipykernel_21880/3343928682.py) in 
      5 
      6 #feed the  inputs to a softmax activation function
----> 7 outputs = tf.keras.activations.softmax(inputs)
      8 print(f'output of softmax function: {outputs.numpy()}')
      9 

[d:\resoluteai\anaconda\lib\site-packages\tensorflow\python\util\traceback_utils.py](file:///D:/resoluteai/anaconda/lib/site-packages/tensorflow/python/util/traceback_utils.py) in error_handler(*args, **kwargs)
    151     except Exception as e:
    152       filtered_tb = _process_traceback_frames(e.__traceback__)
--> 153       raise e.with_traceback(filtered_tb) from None
    154     finally:
    155       del filtered_tb

[d:\resoluteai\anaconda\lib\site-packages\keras\activations.py](file:///D:/resoluteai/anaconda/lib/site-packages/keras/activations.py) in softmax(x, axis)
     90             output = e / s
     91     else:
---> 92         raise ValueError(
     93             f"Cannot apply softmax to a tensor that is 1D. Received input: {x}"
     94         )

ValueError: Cannot apply softmax to a tensor that is 1D. Received input: [1. 3. 4. 2.]

![Screenshot (20)](https://user-images.githubusercontent.com/83391298/224009020-ab048395-10be-44b8-995d-7e5999159683.png)

**Comment by cfav-dev** [comment]
Hi. Unfortunately, I can't reproduce the issue. Next time, you can also report this in our community for better visibility and quicker escalation. The link to join is in Week 1 of your classroom. Thanks!
