### ISSUE TITLE
tensorflow-1-public/C1/W2/ungraded_labs/C1_W2_Lab_1_beyond_hello_world.ipynb  Accuracy vs Loss

### ISSUE THREAD

**Issue by gladwig2** [https-deeplearning-ai/tensorflow-1-public#9]
![image](https://user-images.githubusercontent.com/8951837/129581168-b5c3b429-34aa-40f7-8692-fd1540c435fb.png)

The use of the term 'accuracy' here seems incorrect?
1) logs.get('loss') is going to return the"'sparse_categorical_crossentropy'" loss.
2) accuracy is = #correct_preductions/#Total_predictions

I recommend just saying "Loss < xx%".
This is going to be related to the next couple of issues that relate to the graded assignment.

Lets note at this point that the ungraded lab is using  logs.get('loss')

**Comment by cfav-dev** [comment]
Good point. But we'll also remove this exercise because callbacks are discussed in the next lecture and notebook. Thanks!
