### ISSUE TITLE
C2_W4_Lab_1_multi_class_classifier.ipynb No module named 'keras_preprocessing'

### ISSUE THREAD

**Issue by xyashapyx** [https-deeplearning-ai/tensorflow-1-public#99]
In the "Prepare the ImageDataGenerator" it is needed to replace 
"from keras_preprocessing.image import ImageDataGenerator" 
with 
"from tensorflow.keras.preprocessing.image import ImageDataGenerator"
without this I'm getting the error:

`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-10-ca2960e0dc1a>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from keras_preprocessing.image import ImageDataGenerator
      2 from tensorflow.keras.preprocessing.image import ImageDataGenerator
      3 
      4 TRAINING_DIR = "tmp/rps-train/rps"
      5 training_datagen = ImageDataGenerator(

ModuleNotFoundError: No module named 'keras_preprocessing'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------`

**Comment by cfav-dev** [comment]
Hi! This is now fixed. Thank you for reporting!
